### ISSUE TITLE
DCD output is wrong

### ISSUE THREAD

**Issue by Andrax92** [mubastan/mpeg7fex#1] opened 2017-06-14 17:14 UTC
Hello, I have been using this program  to extract the DCD colors of some images and the colors that come through the output are wrong... I have modified the test project so that it prints the values in an .xml file and the output is this:

<DCDpercentage_0>2</DCDpercentage>
		<DCDcolorValue0_0>0</DCDcolorValue0>
		<DCDcolorValue1_0>0</DCDcolorValue1>
		<DCDcolorValue2_0>0</DCDcolorValue2>
	<DCDpercentage_1>8</DCDpercentage>
		<DCDcolorValue0_1>0</DCDcolorValue0>
		<DCDcolorValue1_1>0</DCDcolorValue1>
		<DCDcolorValue2_1>0</DCDcolorValue2>
	<DCDpercentage_2>11</DCDpercentage>
		<DCDcolorValue0_2>0</DCDcolorValue0>
		<DCDcolorValue1_2>0</DCDcolorValue1>
		<DCDcolorValue2_2>0</DCDcolorValue2>
	<DCDpercentage_3>3</DCDpercentage>
		<DCDcolorValue0_3>0</DCDcolorValue0>
		<DCDcolorValue1_3>0</DCDcolorValue1>
		<DCDcolorValue2_3>0</DCDcolorValue2>
	<DCDpercentage_4>2</DCDpercentage>
		<DCDcolorValue0_4>0</DCDcolorValue0>
		<DCDcolorValue1_4>0</DCDcolorValue1>
		<DCDcolorValue2_4>0</DCDcolorValue2>
	<DCDpercentage_5>2</DCDpercentage>
		<DCDcolorValue0_5>0</DCDcolorValue0>
		<DCDcolorValue1_5>0</DCDcolorValue1>
		<DCDcolorValue2_5>0</DCDcolorValue2>

This has no sense. What cuold the problem be??

**Comment by mubastan** [comment] 2017-06-15 09:59
Hello,

This does not make sense at all. If all the dominant colors were zero, then there would only be a single dominant color! Obviously, your input image is not a black image either!

Can you try the original test code and the FexWrite::computeWriteDCD function to see what output you get?
I suspect you are not using the library correctly or not writing the output correctly.

**Comment by Andrax92** [comment] 2017-06-16 11:18
Hello,

I know that it doesn´t make sense... Thats why I posted the issue. The otiginal test code generates this output: 
![img](https://user-images.githubusercontent.com/6663366/27224598-4fd249cc-5296-11e7-8aff-9cdcae070e93.png)

I only added std::cout << "\n\n Dominant colors\n"; so that the values cuold be easily seen. 
The image that is been analized is motor.jpg.
Thank you for your help.

**Comment by mubastan** [comment] 2017-06-16 13:48
I have just run the test code (test/main.cpp) as it is, and this is what I get for DCD:
`2 1 0 0 8 28 28 28 11 13 14 15 3 11 11 9 2 6 6 7 2 19 20 20`

Earlier 3 descriptor values (CSD, SCD, CLD) are the same as yours.

I run it on Linux (Mint 18.2) and with OpenCV 3.1.0.
There should not be any problem with the previous versions of OpenCV as well, as the original version used earlier releases.

Maybe, you can try compiling with CodeBlocks+MinGW on Windows, to see if the difference is due to compiler/platform (if everything else is the same).

The internal descriptor extraction codes were written by MPEG-7 committee (part of XM Software) and not by me. I actually had spotted few bugs and corrected them. One possibility is that there is some piece of code inside DCD which is not very portable and behaves differently depending on the platform.

**Comment by Andrax92** [comment] 2017-06-16 14:11
Ok, thanks a lot. I will try that.

**Comment by mubastan** [comment] 2018-02-18 04:42
Hi,

If you are still using the library, there are some bug fixes (issue #2 and issue #3), mostly on memory leak, but one with potentially uninitialized dynamic memory (imutil.c, function mergecb) which may have caused your problem. The issues are fixed now.

**Comment by chris1879** [comment] 2018-03-10 17:26
Hi Mubastan

The issue is in module dominantcolorextraction.cpp in the function
DominantColorExtractionTool::Extract

I get the same result as andrax92, I got no colors for motor.jpg.
The reason is that the values for

  colspcpres and colquantpres

 are always set to false. Therefore icnts[i] is always 0 because the condition below is always false.
 The local colspcpres are also not correct, instead there should be the class member colspcpres used!
 
 codesnippet:

  // modified by mb, 24 june 2008
  bool colspcpres = false;
  bool colquantpres = false;

  /* color space conversion & quantization */

  int component0, component1, component2;
  int bin_number0, bin_number1, bin_number2;
  int max_h;
  float *conversionmatrix;

  component0 = 0;
  component1 = 1;
  component2 = 2; // default RGB

  //in ColorSpace.h typedef enum {RGB,YCRCB,HSV,HMMD,LinearMatrix,Monochrome} ColorSpaceType;


  bin_number0 = this->binNum1;
  bin_number1 = this->binNum2;
  bin_number2 = this->binNum3; // default 5 bit


  max_h = 256;

  // This condition is never true, because of the upper definition set to false
  if(colspcpres) {	// currently false
    TPixel in[25];
    TPixel res;
    ....

BR,
Christian

**Comment by mubastan** [comment] 2018-03-11 04:52
Hi Christian,

Thanks for the feedback.
I think, those are not used in the default DCD descriptor, therefore they were set to false (on purpose -- it has been a long time, I do not remember).

I have tried the test code and still got the DCD descriptor above (2 1 0 0 8 28 28 28 11 13 14 15 3 11 11 9 2 6 6 7 2 19 20 20). It might be due to yet another uninitialized memory area, which happens to be initialized to 0 in some cases and work properly.

Please let me know if you can get proper results and how you achieved it.

**Comment by chris1879** [comment] 2018-03-11 14:50
Hi,

I think, I have found the reason for the wrong descriptor from andrax92 and me.

I compiled fex under windows with VC2008, where I noticed, that the function lroundf in imgutil.c
is declared behind(!) the caller "luv2rgb". VC2008 throws only a warning, that it assumes as int.
When you put the function at the beginning of the file, or write a prototype, then all is now working fine and gives me the same result as for you. Great :-)

This function is for other compilers outcommented, but for VC2008 it is necessary.

BR,
Christian

#ifdef Visual_C
int lroundf(float x)
{
  int i;
  float y;

  y=(float)floor(x);
  if ((x-y)>=0.5) x = (float)ceil(x);
  else x = (float)floor(x);
  i = (int) x;
  return i;
}
#endif

**Comment by mubastan** [comment] 2018-03-11 15:04
Great!
I wonder if it works correctly with MinGW compiler (it should). I used to compile it with MinGW (CodeBlocks+MinGW) at that time and was working fine.

**Comment by chris1879** [comment] 2018-03-11 17:42
It is also possible to restrict that code snippet to Microsoft C++. Then it works also fine with MinGW
and is not an impediment for other compilers and platforms.

#ifdef WIN32
#if _MSC_VER < 1600 // for older Visual C 
int lroundf(float x)
{
  int i;
  float y;

  y=(float)floor(x);
  if ((x-y)>=0.5) x = (float)ceil(x);
  else x = (float)floor(x);
  i = (int) x;
  return i;
}
#endif
#endif

**Closed as completed** 2018-10-19 07:35 UTC
